//! The `anb` method and heavy CLI references share one rendering so setup
//! and the committed skill teach the same commands. Worked replies execute
//! against a scratch notebook; CI checks the committed copy for drift.

use crate::cli::{Cli, Command, NARROWING};
use crate::recovery::subject;
use crate::reply::{Host, execute};
use crate::text;
use anb_core::{FindingCode, MemoryStorage, Severity, Storage as _, StorageError};
use clap::{Arg, CommandFactory as _, Parser as _};
use std::fmt::Write as _;
use std::path::Path;

/// The skill's directory name under a host's `skills/`.
pub const NAME: &str = "anb";

pub const SKILL_FILE: &str = "SKILL.md";
pub const COMMANDS_FILE: &str = "references/commands.md";
pub const SESSION_FILE: &str = "references/session.md";
pub const REFUSALS_FILE: &str = "references/refusals.md";

/// The day every example runs on, so the rendering is the same on every
/// machine and the ages in it read as written.
const TODAY: &str = "2026-01-15";
const AUTHOR: &str = "Ada";

/// The skill and the references installed with it.
#[derive(Debug, PartialEq, Eq)]
pub struct Skill {
    pub skill: String,
    pub commands: String,
    pub session: String,
    pub refusals: String,
}

impl Skill {
    #[must_use]
    pub fn files(&self) -> [(&'static str, &str); 4] {
        [
            (SKILL_FILE, &self.skill),
            (COMMANDS_FILE, &self.commands),
            (SESSION_FILE, &self.session),
            (REFUSALS_FILE, &self.refusals),
        ]
    }
}

#[must_use]
pub fn render() -> Skill {
    Skill {
        skill: skill_md(),
        commands: reference(
            "anb commands",
            "Every anb command with its flags, from the definitions anb --help prints. Open before a verb you have not used.",
            commands_section,
        ),
        session: reference(
            "anb worked session",
            "One notebook worked from empty to archived work, every reply as the tool printed it. Open to see what a reply looks like before you parse one.",
            session_section,
        ),
        refusals: reference(
            "anb refusals",
            "Every refusal code with its cause and recovery instruction, and the findings anb check raises. Open when a refusal's suggested correction is not enough.",
            |out| {
                refusals_section(out);
                findings_section(out);
            },
        ),
    }
}

// ---------------------------------------------------------------------------
// SKILL.md — the method
// ---------------------------------------------------------------------------

fn skill_md() -> String {
    let mut out = String::new();
    out.push_str("---\nname: anb\n");
    out.push_str("description: Recall and maintain project memory in repositories using agent-notebook. Use for continuing work, recording decisions or domain knowledge, and applying personal practices across sessions.\n");
    out.push_str("metadata:\n  managed-by: anb\n---\n\n");
    out.push_str(SKILL_BODY);
    out
}

const SKILL_BODY: &str = include_str!("method.md");

fn reference(name: &str, description: &str, section: impl FnOnce(&mut String)) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "---\nname: {name}\ndescription: {description}");
    out.push_str("metadata:\n  managed-by: anb\n---\n\n");
    let _ = writeln!(out, "# {name}\n");
    out.push_str("This reference is generated by `anb skill`. Command descriptions come from the CLI definitions; examples run against a scratch notebook. CI checks the committed copy for drift.\n\n");
    let mut body = String::new();
    section(&mut body);
    out.push_str("## Contents\n\n");
    for heading in headings(&body) {
        let _ = writeln!(out, "- {heading}");
    }
    out.push('\n');
    out.push_str(&body);
    out
}

/// The headings of `body` at its shallowest level: the sections a reader
/// jumps to, listed before the text so a partial read still shows the scope.
fn headings(body: &str) -> Vec<&str> {
    let marked: Vec<(usize, &str)> = body
        .lines()
        .filter_map(|line| {
            let level = line.bytes().take_while(|byte| *byte == b'#').count();
            (level > 0 && line.as_bytes().get(level) == Some(&b' '))
                .then(|| (level, line[level + 1..].trim()))
        })
        .collect();
    let Some(shallowest) = marked.iter().map(|(level, _)| *level).min() else {
        return Vec::new();
    };
    marked
        .into_iter()
        .filter(|(level, _)| *level == shallowest)
        .map(|(_, text)| text)
        .collect()
}

/// Every verb with its flags, from the clap tree the binary parses with.
/// The narrowing flags are one table, since they mean the same on every
/// verb that takes them; a verb's section names the ones it takes.
fn commands_section(out: &mut String) {
    let cli = Cli::command();
    out.push_str("### Global options\n\n| Flag | Meaning |\n|---|---|\n");
    for flag in cli.get_arguments().filter(|arg| arg.is_global_set()) {
        let _ = writeln!(out, "| `{}` | {} |", flag_spelling(flag), flag_help(flag));
    }
    out.push('\n');
    let verbs: Vec<&clap::Command> = cli
        .get_subcommands()
        .filter(|verb| verb.get_name() != "help" && !verb.is_hide_set())
        .collect();

    out.push_str("### Narrowing\n\n");
    out.push_str("A read answers with the records its narrowing admits. Each flag is a predicate over the same notebook, so two flags ask for the intersection, and a flag means the same on every verb that takes it; a verb's section names its own. Without `--by`, `--mine` or `--team`, the notebook's `scope` config key decides whose records a read answers with.\n\n");
    let mut named: Vec<String> = Vec::new();
    out.push_str("| Flag | Meaning |\n|---|---|\n");
    for flag in verbs.iter().flat_map(|verb| narrowing_flags(verb)) {
        if named.contains(&flag_spelling(flag)) {
            continue;
        }
        named.push(flag_spelling(flag));
        let _ = writeln!(out, "| `{}` | {} |", flag_spelling(flag), flag_help(flag));
    }
    out.push('\n');

    for verb in verbs {
        let _ = writeln!(out, "### anb {}", verb.get_name());
        if let Some(about) = verb.get_about() {
            let _ = writeln!(out, "\n{about}\n");
        }
        let positionals: Vec<String> = verb
            .get_positionals()
            .map(|arg| {
                let name = arg.get_id().as_str().to_uppercase();
                if arg.is_required_set() {
                    format!("<{name}>")
                } else {
                    format!("[{name}]")
                }
            })
            .collect();
        if !positionals.is_empty() {
            let _ = writeln!(out, "Arguments: `{}`\n", positionals.join(" "));
        }
        let mut flags = own_flags(verb).peekable();
        if flags.peek().is_some() {
            out.push_str("| Flag | Meaning |\n|---|---|\n");
            for flag in flags {
                let _ = writeln!(out, "| `{}` | {} |", flag_spelling(flag), flag_help(flag));
            }
            out.push('\n');
        }
        let narrowing: Vec<String> = narrowing_flags(verb)
            .map(|flag| format!("`--{}`", flag.get_long().unwrap_or_default()))
            .collect();
        if !narrowing.is_empty() {
            let _ = writeln!(out, "Narrowing: {}.\n", narrowing.join(", "));
        }
    }
}

/// The flags a verb declares for itself: not the global ones, not the
/// shared narrowing.
fn own_flags(verb: &clap::Command) -> impl Iterator<Item = &Arg> {
    verb.get_arguments()
        .filter(|arg| arg.get_long().is_some() && !arg.is_global_set())
        .filter(|arg| arg.get_id().as_str() != "help")
        .filter(|arg| arg.get_help_heading() != Some(NARROWING))
}

/// The narrowing flags a verb takes, under the heading that marks them.
fn narrowing_flags(verb: &clap::Command) -> impl Iterator<Item = &Arg> {
    verb.get_arguments()
        .filter(|arg| arg.get_help_heading() == Some(NARROWING))
}

fn flag_spelling(flag: &Arg) -> String {
    let long = flag.get_long().unwrap_or_default();
    if !flag.get_action().takes_values() {
        return format!("--{long}");
    }
    match flag.get_value_names() {
        Some(names) if !names.is_empty() => format!("--{long} <{}>", names[0].as_str()),
        _ => format!("--{long} <{}>", long.to_uppercase()),
    }
}

fn flag_help(flag: &Arg) -> String {
    flag.get_help()
        .map(|help| help.to_string().replace('\n', " "))
        .unwrap_or_default()
}

/// A reproducible scenario, with replies rendered by the tool.
fn session_section(out: &mut String) {
    out.push_str("Every reply below is what the tool printed, run on ");
    out.push_str(TODAY);
    out.push_str(
        " by an agent working as `Ada`, the identity the host resolved from `ANB_BY` or git.\n\n",
    );
    let mut notebook = Scratch::new();
    for step in SESSION {
        match step {
            Step::Head(text) => {
                let _ = writeln!(out, "## {text}\n");
            }
            Step::Say(text) => {
                let _ = writeln!(out, "{text}\n");
            }
            Step::Run(line) => notebook.example(out, line),
            Step::Report(path, body) => notebook.reports.push((path, body)),
        }
    }
}

/// The refusal catalog: one example per stable code, rendered by the tool.
fn refusals_section(out: &mut String) {
    out.push_str("Refusals carry an `error` code, a `message` explaining the condition and a `try` array of recovery commands. Fill placeholders before running a suggested command. JSON and TOON contain the same values.\n\n");
    let mut notebook = Scratch::new();
    for step in REFUSALS {
        match step {
            Step::Head(text) => {
                let _ = writeln!(out, "## {text}\n");
            }
            Step::Say(text) => {
                let _ = writeln!(out, "{text}\n");
            }
            Step::Run(line) => notebook.example(out, line),
            Step::Report(path, body) => notebook.reports.push((path, body)),
        }
    }
    out.push_str("## Codes without an example\n\n");
    out.push_str("Other refusal codes describe command or storage failures: `unknown-command` (a verb anb does not have; the reply offers `anb --help`), `storage` (the file system failed the read or write, in the message) and `not-utf8` (a record file is not UTF-8; `anb check` names it).\n\n");
}

/// The check findings, code by code, with the weight each carries.
fn findings_section(out: &mut String) {
    out.push_str("## Check findings\n\n");
    out.push_str("`anb check` prints `findings[N]{file,line,severity,code,repair,message}`; an `error` fails the command, a `warning` does not. The `repair` column carries the command that erases the finding when the tool has one.\n\n");
    out.push_str("| Severity | Codes |\n|---|---|\n");
    for severity in [Severity::Error, Severity::Warning] {
        let codes: Vec<String> = FindingCode::ALL
            .iter()
            .filter(|code| code.severity() == severity)
            .map(|code| format!("`{}`", code.as_str()))
            .collect();
        let _ = writeln!(
            out,
            "| {} | {} |",
            match severity {
                Severity::Error => "error",
                Severity::Warning => "warning",
            },
            codes.join(", ")
        );
    }
    out.push('\n');
}

enum Step {
    /// A section heading; the reference lists them at its top.
    Head(&'static str),
    /// Prose between examples.
    Say(&'static str),
    /// A command line, run and rendered.
    Run(&'static [&'static str]),
    /// A file supplied to an example's body-file option.
    Report(&'static str, &'static str),
}

const SESSION: &[Step] = &[
    Step::Head("The hub and the work born inside it"),
    Step::Say(
        "A larger outcome has a hub Task and independently verifiable children. These examples use explicit ids so each command is reproducible:",
    ),
    Step::Run(&[
        "add",
        "task",
        "Ship the parser",
        "--id",
        "task.ship-the-parser",
        "--tag",
        "epic",
        "--body",
        "The parser reads every record file byte for byte.",
    ]),
    Step::Run(&[
        "add",
        "task",
        "Grammar parser accepts fences",
        "--id",
        "task.grammar-parser-accepts-fences",
        "--from",
        "task.ship-the-parser",
        "--priority",
        "1",
    ]),
    Step::Run(&[
        "add",
        "task",
        "Negative corpus wired into CI",
        "--id",
        "task.negative-corpus-wired-into-ci",
        "--from",
        "task.ship-the-parser",
        "--priority",
        "2",
    ]),
    Step::Run(&[
        "block",
        "task.ship-the-parser",
        "task.grammar-parser-accepts-fences",
    ]),
    Step::Run(&[
        "block",
        "task.ship-the-parser",
        "task.negative-corpus-wired-into-ci",
    ]),
    Step::Run(&[
        "block",
        "task.negative-corpus-wired-into-ci",
        "task.grammar-parser-accepts-fences",
    ]),
    Step::Head("The queue"),
    Step::Say(
        "A Task planned for a colleague is handed over as it is written, and the queue shows what can start now: the blocked child waits, the `taken-by` column names who holds a Task, and `--untaken` is the pool, the Tasks nobody holds:",
    ),
    Step::Run(&[
        "add",
        "task",
        "Port the parser to Go",
        "--id",
        "task.port-the-parser-to-go",
        "--priority",
        "3",
        "--taken-by",
        "Grace",
    ]),
    Step::Run(&["ready"]),
    Step::Run(&["ready", "--untaken"]),
    Step::Run(&["ready", "--for", "task.ship-the-parser"]),
    Step::Say(
        "Narrowed to the user's own, with `--mine` or the config key `scope: mine`, a dashboard holds the Tasks the user holds, the records the user wrote and the records waiting on the user; Ada holds nothing yet, so it counts the pool where her next work is:",
    ),
    Step::Run(&["status", "--mine", "--budget", "0"]),
    Step::Head("A session at work"),
    Step::Say(
        "A session takes the top of the pool, which records who holds it as `taken-by`, logs as it goes with the entry signed `by/via`, and parks a doubt without widening its scope, put to the colleague who can settle it:",
    ),
    Step::Run(&["start", "task.grammar-parser-accepts-fences"]),
    Step::Run(&[
        "comment",
        "task.grammar-parser-accepts-fences",
        "fences parse; the indented-body case is next",
        "--via",
        "codex",
    ]),
    Step::Run(&[
        "add",
        "question",
        "Do fences nest?",
        "--id",
        "question.do-fences-nest",
        "--from",
        "task.grammar-parser-accepts-fences",
        "--to",
        "Grace",
    ]),
    Step::Head("Decisions and Notes"),
    Step::Say(
        "A settled rule is a Decision; a shared term is a Note. Related tags aid retrieval, but do not establish agreement or contradiction:",
    ),
    Step::Run(&[
        "add",
        "decision",
        "Fences never nest",
        "--id",
        "decision.fences-never-nest",
        "--kind",
        "rule",
        "--tag",
        "parser",
        "--tag",
        "grammar",
        "--body",
        "A fence closes at the first closing marker. Answers question.do-fences-nest.",
    ]),
    Step::Run(&[
        "add",
        "decision",
        "A fence body is opaque",
        "--id",
        "decision.a-fence-body-is-opaque",
        "--kind",
        "rule",
        "--tag",
        "parser",
        "--tag",
        "grammar",
        "--body",
        "Nothing inside a fence is parsed.",
    ]),
    Step::Run(&[
        "add",
        "note",
        "Fence",
        "--id",
        "note.fence",
        "--kind",
        "term",
        "--by",
        "Grace",
        "--body",
        "A fence is a pair of triple-backtick lines; the parser treats the lines between as one opaque body.",
    ]),
    Step::Say(
        "The standing rules are one listing, read before the work they bind; the same flags narrow `ready` and `graph`:",
    ),
    Step::Run(&["list", "--type", "decision", "--kind", "rule"]),
    Step::Head("Status"),
    Step::Say(
        "Status opens the session with the work: the active Task and its last log line, the queue with who holds each Task, and the open Questions with who asked and whom; an active Task another person holds would carry their name after its title:",
    ),
    Step::Run(&["status", "--budget", "0"]),
    Step::Say(
        "Narrowed to the user's own, it says whose it is and how to widen it, and a colleague's Task is not in it:",
    ),
    Step::Run(&["status", "--mine", "--budget", "0"]),
    Step::Head("Handing the work over for review"),
    Step::Say(
        "The work is handed to Grace for acceptance, and her narrowed Status opens on what waits on her, the review and the doubt, beside the Task planned for her:",
    ),
    Step::Run(&[
        "submit",
        "task.grammar-parser-accepts-fences",
        "--to",
        "Grace",
    ]),
    Step::Run(&["status", "--by", "Grace", "--budget", "0"]),
    Step::Head("Closing a Question"),
    Step::Say("The doubt closes into the record that settled it, and is archived right after:"),
    Step::Run(&[
        "close",
        "question.do-fences-nest",
        "--resolved-by",
        "decision.fences-never-nest",
    ]),
    Step::Run(&["archive", "question.do-fences-nest"]),
    Step::Head("Closing a Task"),
    Step::Say(
        "After acceptance, close with the outcome on the Task and archive that record. The close names newly unblocked work; shared knowledge stays live:",
    ),
    Step::Report(
        "report.md",
        "# Fences\n\nThe parser accepts fenced bodies; the indented case is covered by the corpus.\n",
    ),
    Step::Run(&[
        "close",
        "task.grammar-parser-accepts-fences",
        "--body-file",
        "report.md",
    ]),
    Step::Run(&["archive", "task.grammar-parser-accepts-fences"]),
    Step::Head("Ending without work, pausing"),
    Step::Say(
        "A Task overtaken before it started ends with its reason, from open, whoever holds it, and is archived like any closed record; a pause carries its reason too:",
    ),
    Step::Run(&[
        "close",
        "task.port-the-parser-to-go",
        "--reason",
        "overtaken by decision.a-fence-body-is-opaque",
    ]),
    Step::Run(&["archive", "task.port-the-parser-to-go"]),
    Step::Run(&[
        "hold",
        "task.negative-corpus-wired-into-ci",
        "--reason",
        "waits for the CI runner",
        "--until",
        "2026-01-20",
    ]),
    Step::Head("Reading back, and the gate"),
    Step::Say(
        "Reading back: one record, the whole notebook, the records that are Ada's own, which the hub she wrote and nobody holds is not, the records holding a text with the archive reached, and the gate, which is clean because every settled record was archived as it settled:",
    ),
    Step::Run(&["show", "task.ship-the-parser"]),
    Step::Run(&["list"]),
    Step::Run(&["list", "--mine"]),
    Step::Run(&["list", "--match", "fence", "--archive"]),
    Step::Run(&["check"]),
];

const REFUSALS: &[Step] = &[
    Step::Head("The scratch notebook"),
    Step::Say("The scratch notebook the refusals below run against:"),
    Step::Run(&[
        "add",
        "task",
        "Ship the parser",
        "--id",
        "task.ship-the-parser",
        "--tag",
        "epic",
    ]),
    Step::Run(&[
        "add",
        "task",
        "Grammar parser accepts fences",
        "--id",
        "task.grammar-parser-accepts-fences",
        "--from",
        "task.ship-the-parser",
    ]),
    Step::Run(&[
        "add",
        "decision",
        "Fences never nest",
        "--id",
        "decision.fences-never-nest",
        "--kind",
        "rule",
    ]),
    Step::Run(&[
        "add",
        "note",
        "Fence",
        "--id",
        "note.fence",
        "--kind",
        "term",
    ]),
    Step::Head("unknown-id"),
    Step::Say("No record carries the id."),
    Step::Run(&["start", "task.parser"]),
    Step::Head("invalid-transition"),
    Step::Say(
        "The record's state does not allow the move; the valid moves are listed, each with its command.",
    ),
    Step::Run(&[
        "close",
        "task.ship-the-parser",
        "--body",
        "The parser is verified.",
    ]),
    Step::Head("taken"),
    Step::Say(
        "Another person holds the Task, having started it or been handed it. `start` takes work nobody holds, so a held Task changes hands through `edit --taken-by` first, on purpose.",
    ),
    Step::Run(&[
        "edit",
        "task.grammar-parser-accepts-fences",
        "--taken-by",
        "Grace",
    ]),
    Step::Run(&["start", "task.grammar-parser-accepts-fences"]),
    Step::Head("invalid-argument"),
    Step::Say(
        "A flag or value is invalid for this command or record type. The reply suggests a valid form.",
    ),
    Step::Run(&["add", "decision", "Tabs", "--priority", "2"]),
    Step::Run(&["close", "task.ship-the-parser"]),
    Step::Head("dangling-ref"),
    Step::Say("An envelope reference names a record that does not exist."),
    Step::Run(&["add", "task", "A child", "--from", "task.ghost"]),
    Step::Head("would-cycle"),
    Step::Say("The proposed dependency would create a cycle. The reply prints the cycle."),
    Step::Run(&[
        "block",
        "task.ship-the-parser",
        "task.grammar-parser-accepts-fences",
    ]),
    Step::Run(&[
        "block",
        "task.grammar-parser-accepts-fences",
        "task.ship-the-parser",
    ]),
    Step::Head("unfinished-dependencies"),
    Step::Say(
        "A Task can be started to coordinate its parts, but successful completion requires its prerequisites to be closed. Inspect the listed blockers; do not remove them merely to make closing succeed.",
    ),
    Step::Run(&["start", "task.ship-the-parser"]),
    Step::Run(&[
        "close",
        "task.ship-the-parser",
        "--body",
        "The parser is verified.",
    ]),
    Step::Head("duplicate-id"),
    Step::Say(
        "An existing record reserves its id, including in the archive. Only deleting a record frees its id.",
    ),
    Step::Run(&[
        "add",
        "task",
        "Ship the parser again",
        "--id",
        "task.ship-the-parser",
    ]),
    Step::Head("wrong-type"),
    Step::Say("The id names a type the command does not act on."),
    Step::Run(&["start", "note.fence"]),
    Step::Head("still-referenced"),
    Step::Say(
        "Other records reference this id. The reply identifies the references that prevent deletion.",
    ),
    Step::Run(&["delete", "task.ship-the-parser"]),
    Step::Head("cannot-supersede"),
    Step::Say(
        "The target is not eligible for supersession. Only an active Decision or Note can be replaced.",
    ),
    Step::Run(&["retire", "decision.fences-never-nest"]),
    Step::Run(&[
        "add",
        "decision",
        "Fences nest once",
        "--kind",
        "rule",
        "--supersedes",
        "decision.fences-never-nest",
    ]),
    Step::Head("archived"),
    Step::Say("An archived record is read, never mutated in place; `restore` brings it back."),
    Step::Run(&["archive", "decision.fences-never-nest"]),
    Step::Run(&["edit", "decision.fences-never-nest", "--title", "Fences"]),
    Step::Head("invalid-record"),
    Step::Say(
        "The operation requires a valid record. Read the findings with `check` and follow the suggested repair before retrying.",
    ),
    Step::Run(&["add", "task", "Broken", "--id", "task.broken"]),
    Step::Run(&["start", "task.broken"]),
];

/// A scratch notebook and files supplied to body-file examples.
struct Scratch {
    storage: MemoryStorage,
    reports: Vec<(&'static str, &'static str)>,
}

impl Scratch {
    fn new() -> Self {
        Scratch {
            storage: MemoryStorage::new(),
            reports: Vec::new(),
        }
    }

    /// Run `line` and append the example: the command, then the reply as
    /// the tool prints it, refusals included.
    fn example(&mut self, out: &mut String, line: &[&str]) {
        let mut args = vec!["anb"];
        args.extend_from_slice(line);
        let cli = Cli::try_parse_from(&args).expect("an example is a well-formed command line");
        let subject = subject(&cli.command);
        let reports = &self.reports;
        let read_file = |path: &str| -> Result<String, StorageError> {
            reports
                .iter()
                .find(|(named, _)| *named == path)
                .map(|(_, body)| (*body).to_owned())
                .ok_or_else(|| StorageError::NotFound {
                    path: path.to_owned(),
                })
        };
        let no_lost = |_: &[anb_core::CitedProof]| Vec::new();
        let host = Host {
            session: None,
            identity: || Some(AUTHOR.to_owned()),
            read_file: &read_file,
            lost_proofs: &no_lost,
            user_notebook: None,
            personal_notebook: None,
            audience: crate::recall::Audience::Project,
            project_dir: Path::new("."),
            today: TODAY,
        };
        if matches!(cli.command, Command::Add { .. })
            && line.get(1) == Some(&"task")
            && line.get(2) == Some(&"Broken")
        {
            // The one example no command can produce: a file corrupted by
            // hand, so `invalid-record` has something to show.
            let _ = execute(cli.command, &mut self.storage, host);
            self.storage
                .write(
                    "tasks/task.broken.md",
                    "---\nid: task.broken\ntype: task\nstate: bogus\ntitle: Broken\ncreated: 2026-01-15\n---\n",
                )
                .expect("the scratch notebook is writable");
            return;
        }
        let rendered = match execute(cli.command, &mut self.storage, host) {
            Ok(reply) => text::render(&reply),
            Err(error) => text::render_error(&error, &subject),
        };
        let _ = writeln!(out, "```\n$ anb {}\n{}```\n", shell_words(line), rendered);
    }
}

/// The command line as a reader types it: a word with a space is quoted.
fn shell_words(line: &[&str]) -> String {
    line.iter()
        .map(|word| {
            if word.contains(' ') || word.is_empty() {
                format!("\"{word}\"")
            } else {
                (*word).to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_rendering_is_deterministic() {
        assert_eq!(render(), render());
    }

    #[test]
    fn a_reference_opens_with_the_list_of_its_sections() {
        let skill = render();
        for (file, text) in &skill.files()[1..] {
            let (_, after) = text
                .split_once("## Contents\n\n")
                .unwrap_or_else(|| panic!("{file} has no contents list"));
            let listed: Vec<&str> = after
                .lines()
                .map_while(|line| line.strip_prefix("- "))
                .collect();
            let body = &after[listed.iter().map(|item| item.len() + 3).sum::<usize>()..];
            let marks = |line: &str| line.bytes().take_while(|byte| *byte == b'#').count();
            let shallowest = body
                .lines()
                .filter(|line| line.starts_with('#'))
                .map(marks)
                .min()
                .unwrap_or_else(|| panic!("{file} has no sections"));
            let sections: Vec<&str> = body
                .lines()
                .filter(|line| {
                    marks(line) == shallowest && line.as_bytes().get(shallowest) == Some(&b' ')
                })
                .map(|line| line[shallowest + 1..].trim())
                .collect();
            assert_eq!(listed, sections, "{file} lists other sections than it has");
        }
    }

    #[test]
    fn every_verb_but_help_has_a_commands_entry() {
        let commands = render().commands;
        for verb in Cli::command().get_subcommands() {
            if verb.get_name() == "help" || verb.is_hide_set() {
                continue;
            }
            assert!(
                commands.contains(&format!("### anb {}\n", verb.get_name())),
                "{} is missing from the commands reference",
                verb.get_name()
            );
        }
    }

    #[test]
    fn every_example_ran_and_no_example_broke_by_accident() {
        let Skill {
            session, refusals, ..
        } = render();
        // A worked-session step that failed would render as a refusal in
        // the session; the refusals belong to their own file.
        assert!(
            !session.contains("\nerror:"),
            "a session step was refused:\n{session}"
        );
        assert!(refusals.contains("error: unknown-id"), "{refusals}");
    }
}
